"""update table with created , modified_at column's

Revision ID: 1692146b155d
Revises: 8498474fdb45
Create Date: 2025-10-13 12:41:39.299131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1692146b155d'
down_revision: Union[str, Sequence[str], None] = '8498474fdb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizing_tool', sa.Column('fluid_state_id', sa.Integer(), nullable=True))
    op.add_column('sizing_tool', sa.Column('format_id', sa.Integer(), nullable=True))
    op.add_column('sizing_tool', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('sizing_tool', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sizing_tool', sa.Column('modified_by', sa.String(), nullable=True))
    op.add_column('sizing_tool', sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sizing_tool', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('sizing_tool', 'format')
    op.drop_column('sizing_tool', 'fluid_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizing_tool', sa.Column('fluid_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sizing_tool', sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('sizing_tool', 'parameters',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('sizing_tool', 'modified_at')
    op.drop_column('sizing_tool', 'modified_by')
    op.drop_column('sizing_tool', 'created_at')
    op.drop_column('sizing_tool', 'created_by')
    op.drop_column('sizing_tool', 'format_id')
    op.drop_column('sizing_tool', 'fluid_state_id')
    # ### end Alembic commands ###
