"""add pages_per_value to customer

Revision ID: 19a1d883c518
Revises: e4c7b147eb16
Create Date: 2025-07-07 17:57:19.575153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a1d883c518'
down_revision: Union[str, Sequence[str], None] = 'e4c7b147eb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('pages_per_valve', sa.Integer(), nullable=True))
    op.drop_column('customers', 'pages_per_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('pages_per_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'pages_per_valve')
    # ### end Alembic commands ###
