"""update table name standard_parameters 

Revision ID: 2a576f71c2cf
Revises: 1692146b155d
Create Date: 2025-10-14 12:02:01.341045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a576f71c2cf'
down_revision: Union[str, Sequence[str], None] = '1692146b155d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sizing_tool')
    op.add_column('documents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('documents_uploaded_by_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'])
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'uploaded_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_user_id_fkey'), 'documents', 'users', ['uploaded_by_user_id'], ['id'])
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'created_by')
    op.create_table('sizing_tool',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parameters', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fluid_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('modified_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sizing_tool_pkey'))
    )
    # ### end Alembic commands ###
