"""add pages_per_value to customer

Revision ID: 3b7ca9f91b0a
Revises: f98e49b5bb45
Create Date: 2025-07-09 10:14:29.792337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7ca9f91b0a'
down_revision: Union[str, Sequence[str], None] = 'f98e49b5bb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
