"""add pages_per_value to customer

Revision ID: 5449bae79460
Revises: 19a1d883c518
Create Date: 2025-07-08 10:17:30.748198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5449bae79460'
down_revision: Union[str, Sequence[str], None] = '19a1d883c518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_templates', sa.Column('ocr_boxes', sa.JSON(), nullable=True))
    op.add_column('extraction_templates', sa.Column('box_mappings', sa.JSON(), nullable=True))
    op.drop_column('extraction_templates', 'ocr_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_templates', sa.Column('ocr_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('extraction_templates', 'box_mappings')
    op.drop_column('extraction_templates', 'ocr_boxes')
    # ### end Alembic commands ###
