"""adding the columns like email , address , created_at , created_by , modified_at , modified_by , is_active on Customer table

Revision ID: 9abc67cfefb4
Revises: efe070df23fc
Create Date: 2025-09-25 14:46:44.255507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abc67cfefb4'
down_revision: Union[str, Sequence[str], None] = 'efe070df23fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('modified_by', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'modified_by')
    op.drop_column('customers', 'modified_at')
    op.drop_column('customers', 'created_by')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
