"""changes on the is_active column

Revision ID: a260b3ee70e3
Revises: 9abc67cfefb4
Create Date: 2025-09-25 16:13:23.224939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a260b3ee70e3'
down_revision: Union[str, Sequence[str], None] = '9abc67cfefb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'customers',
        'is_active',
        existing_type=sa.Boolean(),
        server_default=sa.sql.expression.true()  # set default True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
