"""drop the pages_per_valve column from the customer table

Revision ID: efe070df23fc
Revises: 3b7ca9f91b0a
Create Date: 2025-09-25 12:51:23.588577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe070df23fc'
down_revision: Union[str, Sequence[str], None] = '3b7ca9f91b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'pages_per_valve')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('pages_per_valve', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
