"""add pages_per_value to customer

Revision ID: f98e49b5bb45
Revises: 5449bae79460
Create Date: 2025-07-08 11:18:06.241649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98e49b5bb45'
down_revision: Union[str, Sequence[str], None] = '5449bae79460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'extraction_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'template_id')
    # ### end Alembic commands ###
